version: 2
jobs:
  build:
    docker:
      - image: docker:18.01.0-ce-git
    working_directory: /tmp/src/xnat_downloader
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          no_output_timout: 60m
          command: |
            docker build \
            -t hbclab/xnat_downloader:latest \
            --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg VCS_REF=`git rev-parse --short HEAD` \
            --build-arg VERSION="${CIRCLE_TAG:-$THISVERSION}" .
      - run:
          name: Execute Docker image
          command: |
            docker run -ti --rm \
            hbclab/xnat_downloader:latest --help
      - run:
          name: Run Docker image on test data
          command: |
            docker run -ti --rm=false --name xnat_app \
            hbclab/xnat_downloader:latest \
            -i /opt/xnatDownloader/tests/circleci_test.json \
            -c /opt/xnatDownloader/tests/central.cfg
      - run:
          name: Check for output
          command: |
            mkdir -p /tmp/xnat/bids
            docker cp xnat_app:/out /tmp/xnat/bids

      - run:
          name: Validate output
          command: |
            mkdir -p /tmp/test
            find /tmp/xnat/bids/out -type f | sed s+/tmp/xnat/bids/out/++ | sort > /tmp/test/extend.out
            diff /tmp/src/xnat_downloader/.circleci/extend.txt /tmp/test/extend.out
            exit $?
